[project]
name = "sv-env-code-vulnerability"
description = "Security Verifiers environment: Vulnerability Assessment in Code Snippets (ToolEnv/MultiTurnEnv)"
tags = [
  "intertwine",
  "security-verifiers",
  "security",
  "cybersecurity",
  "multi-turn",
  "code-security",
  "vulnerability-detection",
  "static-analysis",
  "sast",
  "tools",
  "sandbox",
  "train",
  "eval",
]
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "verifiers>=0.1.4",
  "datasets>=2.0.0",
  "pandas>=2.0.0",
  "bandit>=1.7.0",
  "ast-grep-py>=0.38.0",
  "tree-sitter>=0.20.0",
  "tree-sitter-python>=0.20.0",
  "tree-sitter-c>=0.20.0",
  "semgrep>=1.45.0",
  "unidiff>=0.7.5",
]

[project.entry-points."verifiers.environments"]
sv-env-code-vulnerability = "sv_env_code_vulnerability:load_environment"

[project.optional-dependencies]
dev = [
  "pytest>=7.0.0",
  "ruff>=0.12.11",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["sv_env_code_vulnerability.py", "sv_env_code_vulnerability_test.py"]

[tool.pytest.ini_options]
filterwarnings = ["ignore:ast.Str is deprecated:DeprecationWarning"]
python_files = ["*_test.py"]
testpaths = ["."]

[tool.ruff]
line-length = 120
