name: Build Wheels

on:
  workflow_dispatch:  # Manual trigger
  push:
    tags:
      - 'v*'  # Trigger on version tags

jobs:
  build-wheels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build wheel setuptools

      - name: Build all environment wheels
        run: |
          # Build each environment
          for env in environments/*/; do
            if [ -f "$env/pyproject.toml" ]; then
              echo "Building wheel for $env..."
              cd "$env"
              python -m build --wheel --outdir dist
              cd ../..
            fi
          done
          
          # Create a combined dist directory
          mkdir -p dist
          cp environments/*/dist/*.whl dist/ 2>/dev/null || true

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: python-wheels
          path: dist/*.whl
          if-no-files-found: error

      - name: List built wheels
        run: |
          echo "Built wheels:"
          ls -la dist/*.whl || echo "No wheels found"