name: CI

on:
  push:
    branches: [ main, master, "**" ]
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: python -m pip install --upgrade pip uv

      - name: Create venv and install packages
        shell: bash
        run: |
          PY=$(python -c 'import sys; print(sys.executable)')
          uv venv --python="$PY"
          source .venv/bin/activate
          uv pip install -e environments/sv-env-prompt-injection \
            -e environments/sv-env-secrets-leakage \
            -e environments/sv-env-tool-use-safety \
            -e environments/sv-env-code-exec-safety \
            -e environments/sv-env-network-safety \
            -e environments/sv-env-policy-compliance
          uv pip install pytest ruff build

      - name: Lint
        run: uv run ruff check .

      - name: Format
        run: uv run ruff format .

      - name: Format check
        run: uv run ruff format --check .

      - name: Tests
        run: uv run pytest -q

